### ISSUE TITLE
Safe_perc invalid syntax

### ISSUE THREAD

**Issue by washlet** [KgBC/just-dice-bot#10]
After fighting with python and pip I could get almost everything to work.
Now, when I run the bot it says:
http://img16.imageshack.us/img16/5576/nprg.png

**Comment by KgBC** [comment]
I'm sorry, there's a typo in default config.

```
jdb_config = {
    "visible"    : 1,
    "user"       : "YOUR_USER",
    "pass"       : "YOUR_PASSWORD",
    "lose_rounds": 30,
    "chance"     : 49.5,
    "multiplier" : 2.0, #<-- here is a comma missing.
    "safe_perc"  : 5.0,
    "auto-tip"   : 1,
}
```

Will correct in source.
