### ISSUE TITLE
Wrong bet

### ISSUE THREAD

**Issue by comor** [KgBC/just-dice-bot#12]
In new version after 4,5 hours running bot tried to bet >100 BTC. Balance was 0.1 :)

**Comment by comor** [comment]
Forgot to mension. I used commented part of config.

**Comment by KgBC** [comment]
Could you pass me some lines of output? Never happened to me...
and your config WITHOUT User/Password

**Comment by comor** [comment]
Nothing uncommon in output :/

**Comment by KgBC** [comment]
The config is this?

```
jdb_config = {
    "visible" : 1,
    "user" : "YOUR_USER",
    "pass" : "YOUR_PASSWORD",
    "lose_rounds": 27,
    "chance" : 49.5,
    "multiplier" : #rounds
    [ 3.0, 2.5, 2.0]+ #0,1,2 maximizes win
    [ 1.75 for x in range( 3, 7)]+ #3-6 win less every round
    [ 1.5 for x in range( 7,13)]+ #7-12 win less every round
    [ 1.1], # -lose_rounds covers parts of the loss
    "safe_perc" : 5.0,
    "auto-tip" : 1,
}
```

When did it happen - was it a losing streak? How often was the bet raised?

**Comment by KgBC** [comment]
And if I may ask: what was your balance and your expected bet / made bet (as exact as possible)

**Comment by comor** [comment]
config:

```
jdb_config = {
    "visible"    : 1,
    "user"       : "",
    "pass"       : "",
    "lose_rounds": 27,
    "chance"     : 49.5,
    "multiplier" :                           #rounds
            [ 3.0, 2.5, 2.0]+                #0,1,2 maximizes win
            [ 1.75 for x in range( 3, 7)]+   #3-6   win less every round
            [ 1.5  for x in range( 7,13)]+   #7-12  win less every round
            [ 1.1],                          # -lose_rounds covers parts of the loss
    "safe_perc"  : 5.0,
    "auto-tip"   : 0,
}
```

It happend after 1 lose. 
Ballance was 0.1 BTC, 1st bet ~0,000014.

**Comment by KgBC** [comment]
so we know, balance 0.1, bet >100 btc after one lose using the config above. 
First bet: 0,000014

So calculation for first bet: 0.1/3/2.5/(1.75_4)/(1.5_6)/(1.1_13) = 0.00001480001
First bet was correct as it seems.
Second bet should be around 0.00001480_3 = 0.00004440, so why >100.0?

Let me review code and site behavior.

**Comment by comor** [comment]
It wasn't second bet - it was bet after few hours bots running. Starting balance was 0.1, during error balance also ~0.1.

**Comment by KgBC** [comment]
I just discovered an issue with calculation. please immediate update: https://github.com/KgBC/just-dice-bot/issues/13

I've no idea for now why it is doing such a high bid. next on release plan is logging, so with next version we could possibly track it down.

Closing here for now.

**Comment by KgBC** [comment]
logging implemented. please post log if something like that happens again. 
Log doesn't include user/pass. It does include all other parameters and bets.

If your logfile get's long cut it, but leave the settings and some bets before it failed there.
