### ISSUE TITLE
wrong bet calculation - what have I missed?

### ISSUE THREAD

**Issue by KgBC** [KgBC/just-dice-bot#13]
continuously in Log - bets with +0.00000000 cause of not enough funds:

```
5:21:43: +0.00000000 = 0.09810466: -0.19894698 WIN  (-0.89048433(-907.7%)/d), max rows: 237
```

Losing streak ends after 12 rounds, should be 25 rounds.

![jderr](https://f.cloud.github.com/assets/5054214/893539/7f5f748a-faa7-11e2-9bbb-77a05bbefdc1.jpg)

**Comment by KgBC** [comment]
didn't add costs from pre rounds. so I went up to the double balance, and went down again :) my bad.
FIXED! Update immediatly.

**Comment by comor** [comment]
Check this out. Don't have logs - in happend on previous bot version after ~5h running
![zrzut ekranu 2013-08-2 o 00 37 11](https://f.cloud.github.com/assets/5123209/897892/48615016-fafc-11e2-859f-058165deabc6.png)

**Comment by KgBC** [comment]
not realated to that issue. please use a new issue for every problem.
as this is an old version and lot changed in the meanwhile I leave it closed here.
