### ISSUE TITLE
self.get_multiplyer

### ISSUE THREAD

**Issue by ghost** [KgBC/just-dice-bot#16]
root@oxi-ubuntu:/home/oxi# python bot.py 

Simple martingale bot for just-dice.com
Copyright (C) 2013 KgBC IFGIWg@tormail.org
under GPLv2 (see source)

News/new versions see https://github.com/KgBC/just-dice-bot

Set up selenium (this will take a while, be patient) ...
Login (still be patient) ...
--- press 'q|quit' to quit, 'h|?|help' for command help ---
---       finish your commands with the ENTER key       ---
Start betting ...
Traceback (most recent call last):
  File "bot.py", line 315, in <module>
    JustDiceBet()
  File "bot.py", line 88, in **init**
    bet = self.get_max_bet()
  File "bot.py", line 190, in get_max_bet
    multi = self.get_multiplyer(round-2)   #array pos 0 = round 2
  File "bot.py", line 289, in get_multiplyer
    if type(m) is str:
UnboundLocalError: local variable 'm' referenced before assignment

**Comment by KgBC** [comment]
fixed. I'm uploading.
