### ISSUE TITLE
I lost all my money with this bug!!!!!

### ISSUE THREAD

**Issue by ghost** [KgBC/just-dice-bot#17]
root@oxi-ubuntu:/home/oxi# python bot.py 

Simple martingale bot for just-dice.com
Copyright (C) 2013 KgBC IFGIWg@tormail.org
under GPLv2 (see source)

News/new versions see https://github.com/KgBC/just-dice-bot

Set up selenium (this will take a while, be patient) ...
Login (still be patient) ...
--- press 'q|quit' to quit, 'h|?|help' for command help ---
---       finish your commands with the ENTER key       ---
Start betting ...
Exception float division by zero, retrying...
Traceback (most recent call last):
  File "bot.py", line 125, in **init**
    win_24h = self.total*day_sec/difftime_sec
ZeroDivisionError: float division by zero

^C
You lost -0.36114504 since 0:00:00 (this session)
You know, it's betting, so losing is normal.
You may want to take less risk, see README: https://github.com/KgBC/just-dice-bot 
If settings are unclear just file an issue on GitHub. I'll help. Thanks.

Shutting down...

**Comment by ghost** [comment]
oxi (2683) date: 2013-08-02 08:49:01 betid: 42983824 lucky: 13.5102 target: >50.4999 bet: 0.36114504 payout: 2x profit: -0.36114504

This was all my money...

**Comment by KgBC** [comment]
I'm sorry to hear that, almost same happened to me, lost around 0.4.
Yesterday when I found this rounds calculations bug it was fixed and uploaded within 1,5h.

Anyway: you know it's betting, and bad things could happen. And this is open source in an early stage.

Again: I'm sorry to hear you lost. I do my best to make the code stable and bug free as fast as possible.

**Comment by ghost** [comment]
A little info about this error would have been nice, because now the gambling is over for me.

**Comment by KgBC** [comment]
https://github.com/KgBC/just-dice-bot/commits/master
^^ there is that info. 

 SECURITY UPDATE: immediate update … 

You know, I have no mailing list or something, so no way to inform you directly.
The best option was a git commit, because the fist line of my commit log is shown above the downloadable files.

**Comment by KgBC** [comment]
Forgot to mention: I know it is not helping you right now, but there will be a simulation mode soon. To run specific settings simulated over 1000s of random rounds fairly fast. I need it to test settings without losing money, development cost currently include about 100 bucks in losses for testing :)
