### ISSUE TITLE
Error 10083

### ISSUE THREAD

**Issue by geekium** [KgBC/just-dice-bot#20]
The cmd window always throw the 10083 error but the function seems working well nonetheless. Maybe this cause the auto-tip function not working?

On windows 7(Simplified Chinese Language edition) with firefox 22.0.
![2013-08-04_092353](https://f.cloud.github.com/assets/16434/906463/2aa284e6-fca5-11e2-8578-10eb2538b4f7.png)

Traceback (most recent call last):
  File "just-dice-bot.py", line 478, in <module>
    JustDiceBet()
  File "just-dice-bot.py", line 278, in **init**
    if sys.stdin in select.select([sys.stdin], [], [], s)[0]:
select.error: (10038, '')

**Comment by KgBC** [comment]
seems this call isn't working on windows, wonder why it's not documented in the python docs :)
I'll implement an alternative.

**Comment by KgBC** [comment]
btw: did you get this error earlier during betting too? I'm using this construct twice.

**Comment by KgBC** [comment]
done. New version up in 15 minutes.
