### ISSUE TITLE
BAN

### ISSUE THREAD

**Issue by karnevskis6** [KgBC/just-dice-bot#26]
Why I get 1h ban ? is there any fixes in bot more delay, etc?

**Comment by KgBC** [comment]
sry for the long delay, what happened exactly?

**Comment by CriticalNix** [comment]
Just-Dice have chanced their policy on how many bets per second you can make. if your bot is seen to bet more than the allocated time it will auto-ban you for a short period of time.

bets of 0.00000000 BTC are delayed by 3 seconds
bets of 0.00000001 BTC to 0.00000009 BTC are delayed by 1 second
bets of 0.00000010 BTC to 0.00000099 BTC are delayed by 0.8 seconds
bets of 0.00000100 BTC to 0.00000999 BTC are delayed by 0.6 seconds
bets of 0.00001000 BTC to 0.00009999 BTC are delayed by 0.4 seconds
bets of 0.00010000 BTC to 0.00099999 BTC are delayed by 0.2 seconds
bets of 0.00100000 BTC or more are not delayed

**Comment by KgBC** [comment]
working on it
