### ISSUE TITLE
is_element_present

### ISSUE THREAD

**Issue by 544449** [KgBC/just-dice-bot#33]
function "is_element_present" is missing in in class JustDice_impl().

copy it from class JustDiceBet().

also isn't there infinite loop in function do_autotip?

**Comment by KgBC** [comment]
You're right, seems I mixed things up with implementing the simulation mode. As I do not tip myself I didn't see it :)
And yes, it looks like an infinite loop, glad it didn't work at all :p

Thanks for bringing my attention to it, will fix as soon as possible.

**Comment by KgBC** [comment]
fixed in next release
