### ISSUE TITLE
lost

### ISSUE THREAD

**Issue by karnevskis6** [KgBC/just-dice-bot#39]
2013-10-26 08:43:09,427, INFO:   +0.2%luck round  1|B 27093/15:10:05: -0.00001010-h --- (90.0%) = 0.24391063 total. session: +0.04069681 (+0.06439345(+026.4%)/d)
2013-10-26 08:43:11,986, INFO:   +0.2%luck round  2|B 27094/15:10:07: -0.00011120-h --- (90.0%) = 0.24379943 total. session: +0.04058561 (+0.06421515(+026.3%)/d)
2013-10-26 08:43:13,973, INFO:   +0.2%luck round  3|B 27095/15:10:09: -0.00122330-l --- (90.0%) = 0.24257613 total. session: +0.03936231 (+0.06227735(+025.7%)/d)
2013-10-26 08:43:15,753, INFO:   +0.2%luck round  4|B 27096/15:10:11: -0.01345640-l --- (90.0%) = 0.22911973 total. session: +0.02590591 (+0.04098571(+017.9%)/d)
2013-10-26 08:43:17,529, INFO:   +0.2%luck round  5|B 27097/15:10:13: -0.14802050-l --- (90.0%) = 0.08109923 total. session: -0.12211459 (-0.19319028(-238.2%)/d), max lost: -0.16282150, max rows: 5

how it is posible? usually max lost ar 2 times

**Comment by KgBC** [comment]
Hi, I would need your config without user/password to check.

**Comment by KgBC** [comment]
Aw ... you have 

```
90 % chance and
11x multiplier
```

If that's right the math is correct, probably your config is not what you want! You'll need a lot of money for that. 

--- edit ---
corrected my assumptions. 

I'm wating for your configuration to see more. Losing 5 times isn't uncommon at 90%.

**Comment by karnevskis6** [comment]
```
#jdb_config = {
#    "visible"    : 1,                  #1 = show selenium browser automation (slower, but you see what happens, dont use in productive)
#    "user"       : "",         #your user and password on just-dice
#    "pass"       : "",
#    "lose_rounds": 30,                 #bet, so that we could lose for X rounds. Minimum bet is 0.00000001.
#    "chance"     : 90,
#    "min_bet"    : 0.00001000,         #which chance do we want to bet on
#    "multiplier" : 11.0,                   #multiply bet by X on lose
#    "safe_perc"  : 5.0,                 #percent of balance is NOT used for first bet calculation
#    "auto-tip"   : 1,                   #IMPORTANT: 
                                        #This is my deal: I made the bot, which gathers you BTC. 
                                        #I'll support your as long as enough donations come in.
                                        #So if you win, the bot sends X percent (default: 1%) to me. 
                                        #Let the bot builder life :D We will have nice winnings together :)
#}
```

I'm clicked with hand on lo 5h. No rest time. 2 times max lost.

---edit--- formatting corrected

**Comment by KgBC** [comment]
Yes, here we see the issue ... your config says:

```
"chance" : 90, #bet at 90% chance, 
"multiplier" : 11.0, #if lose multiply by 11
"lose_rounds": 30, #you want to play 30 rounds (alot for 11x multiplyer each round)
#here comes the error:
"min_bet" : 0.00001000, #starting bet is 0.00001000
```

Your balance: 0.24391063. So starting from that minimum bet, you lost 5 Rounds and your funds are gone. Next iteration would need another 1.61 BTC (multiply last bet by 11)

There was also a warning, that you couldn't play this betting theme for 30 rounds, you probably ignored that warning with Enter.

About probabilities:
- Round 1: 1 in 10 will lose
- losing 2 rounds in a row: 1 in 100 will lose
- losing 3 rounds in a row: 1 in 1000
- losing 4 ... 1 in 10.000
- losing 5 rounds in a row: 1 in 100000 will lose. 
  According to that, it is likely to get complete broke in 50000 bets. It may happen on your first bets too, these are just probabilities. 

So as this is no error, just misconfiguration, I'll close here. If you have questions feel free to ask anyway.
King regards, KgBC.

**Comment by karnevskis6** [comment]
if it posible, to set only to bet on lo or hi ?

**Comment by KgBC** [comment]
Sure, check the "hi_lo"-parameter in config.

It's documented here: https://github.com/KgBC/just-dice-bot/blob/aces/config-DEFAULT.py
