### ISSUE TITLE
When I will start the bot.

### ISSUE THREAD

**Issue by ghost** [KgBC/just-dice-bot#7]
Traceback (most recent call last):
  File "bot.py", line 155, in <module>
    JustDiceBet()
  File "bot.py", line 46, in **init**
    self.setUp()
  File "bot.py", line 87, in setUp
    EasyProcess('fvwm').start()
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/**init**.py", line 260, in start
    raise EasyProcessError(self, 'start error')
easyprocess.EasyProcessError: start error <EasyProcess cmd_param=fvwm alias={alias} cmd=['fvwm'] ({scmd}) oserror=[Errno 2] No such file or directory returncode=None stdout="None" stderr="None" timeout=False>

**Comment by KgBC** [comment]
Hello, is fvwm installed? See readme for install instructions.
Ah ... missed that in install instructions:

try: sudo apt-get install fvwm

You wouldn't need it with self.visible = 0, but if your want to see what happens I init a window manager to get firefox maximized.

Please give me feedback if this works.

**Comment by ghost** [comment]
After that:
sudo apt-get install fvwm

It works :)

Thank you
