### ISSUE TITLE
Bot stops at just-dice Welcome screen

### ISSUE THREAD

**Issue by rydor85** [KgBC/just-dice-bot#8]
Popup that says we'll call you Stephanie and then nothing happens. login information is correct.

**Comment by KgBC** [comment]
The bot has a long wait time at the start - have you waited > 60 seconds?

**Comment by rydor85** [comment]
That might explain it, I just removed the extra condition and loaded it straight into the class id click at welcome screen (as it doesnt seem to save a site cookie) no matter what the welcome screen always pops, so using that I was able to just assume so and call the click operation.

**Comment by KgBC** [comment]
It should work if you just wait. Well, it must, but you may want to run it with visible=0 later (which is faster and not showing anything but console output).

Does it work when you just wait after starting it?

**Comment by rydor85** [comment]
I don't know tbh, I removed the wait code because of the fact it never saves my login info. starts up quicker this way too.

**Comment by KgBC** [comment]
Well, if you just removed the wait it should work without removing too.
The wait code is needed for slow computers, As I run it on a busy machine that makes sense for me.

If you want me to review your changes feel free to submit a patch.

I'm closing here, I think this is solved.
